language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

install:
  - '[[ -z "$CI_USER_TOKEN" ]] || composer config github-oauth.github.com ${CI_USER_TOKEN};'
  - travis_retry composer self-update && composer --version
  - composer require --no-update codeception/module-asserts:"dev-master"
  - composer require --no-update codeception/module-filesystem:"dev-master"
  - composer require --no-update codeception/codeception:"4.0.x-dev"
  - travis_retry composer update --prefer-dist --no-interaction

  - git clone -q --depth=1 https://github.com/Codeception/yii2-tests framework-tests
  - git --git-dir framework-tests/.git log -n 1
  - travis_retry composer update -d framework-tests --no-dev --prefer-dist --no-interaction
  - php ./vendor/bin/codecept build -c framework-tests

script:
  - php ./vendor/bin/codecept run -c framework-tests
